[build]
target = "x86_64-unknown-uefi"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-unknown-uefi]
rustflags = ["-C", "link-arg=-nostartfiles"]